[package]
name = "kalavara"
version = "0.1.0"
authors = ["Shanavas M <shanavas.m2@gmail.com>"]
edition = "2018"

[dependencies]
argparse = "0.2.2"
md5 = "0.6.1"
rocksdb = "0.12.1"
tempfile = "3.0.7"
tiny_http = "0.6.2"

[build-dependencies]
clippy = { version = "*", optional = true }
